package VistasAdminGeneral;

import Modelos.Persona;
import Vistas.VentanaLogin;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author diaza
 */
public class VentanaMenuPrincipalAdmGeneral extends javax.swing.JFrame {

    private Persona administradorGeneral;
        
    /**
     * Creates new form VentanaMenuPrincipalAdmGeneral
     */
    public VentanaMenuPrincipalAdmGeneral(Persona adminGeneral) {
        initComponents();
        this.administradorGeneral = adminGeneral;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelGestMant = new javax.swing.JPanel();
        btnGestionGestor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelGestAero = new javax.swing.JPanel();
        btnGestionAerolineas = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelAtender = new javax.swing.JPanel();
        btnSolicitudesMantenimiento = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        panelGestuAdmin = new javax.swing.JPanel();
        btnGestionAdminAero = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        btnVolver = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 92, 117));
        jLabel1.setText("ADMIN GENERAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gestión-de-clientes-80.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 80, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 92, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("empleados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 150, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(65, 92, 117));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aerolínea");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 230, 10));

        panelGestMant.setBackground(new java.awt.Color(65, 92, 117));

        btnGestionGestor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGestionGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionGestor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionGestor.setText("Gestionar gestor de mantenimiento");
        btnGestionGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionGestorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionGestorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionGestorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGestMantLayout = new javax.swing.GroupLayout(panelGestMant);
        panelGestMant.setLayout(panelGestMantLayout);
        panelGestMantLayout.setHorizontalGroup(
            panelGestMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestMantLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGestionGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGestMantLayout.setVerticalGroup(
            panelGestMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestMantLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGestionGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelGestMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aerolinea.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(65, 92, 117));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestionar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(65, 92, 117));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("mantenimineto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 200, 30));

        panelGestAero.setBackground(new java.awt.Color(65, 92, 117));

        btnGestionAerolineas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGestionAerolineas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionAerolineas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionAerolineas.setText("Agregar aerolínea");
        btnGestionAerolineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionAerolineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionAerolineasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionAerolineasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionAerolineasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGestAeroLayout = new javax.swing.GroupLayout(panelGestAero);
        panelGestAero.setLayout(panelGestAeroLayout);
        panelGestAeroLayout.setHorizontalGroup(
            panelGestAeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionAerolineas, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        panelGestAeroLayout.setVerticalGroup(
            panelGestAeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestAeroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGestionAerolineas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelGestAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 270, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(65, 92, 117));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gestionar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(65, 92, 117));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Solicitud");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 30));

        panelAtender.setBackground(new java.awt.Color(65, 92, 117));

        btnSolicitudesMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSolicitudesMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitudesMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSolicitudesMantenimiento.setText("Atender solicitudes de mantenimiento");
        btnSolicitudesMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitudesMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSolicitudesMantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSolicitudesMantenimientoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAtenderLayout = new javax.swing.GroupLayout(panelAtender);
        panelAtender.setLayout(panelAtenderLayout);
        panelAtenderLayout.setHorizontalGroup(
            panelAtenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitudesMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        panelAtenderLayout.setVerticalGroup(
            panelAtenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitudesMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 270, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarioimagen.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 30, 30));

        panelGestuAdmin.setBackground(new java.awt.Color(65, 92, 117));

        btnGestionAdminAero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGestionAdminAero.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionAdminAero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionAdminAero.setText("Gestionar Aerolíneas");
        btnGestionAdminAero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionAdminAeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionAdminAeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionAdminAeroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGestuAdminLayout = new javax.swing.GroupLayout(panelGestuAdmin);
        panelGestuAdmin.setLayout(panelGestuAdminLayout);
        panelGestuAdminLayout.setHorizontalGroup(
            panelGestuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestuAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGestionAdminAero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGestuAdminLayout.setVerticalGroup(
            panelGestuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestuAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGestionAdminAero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelGestuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 230, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(65, 92, 117));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Aerolíneas");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 130, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(65, 92, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Crear nueva");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aviones.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, 70));

        jMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver.setText("Mas opciones");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnVolver.add(btnRegresar);

        jMenuBar.add(btnVolver);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        this.dispose();
        JFrame v2 = new VentanaLogin();
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnGestionGestorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionGestorMouseClicked
        this.dispose();
        JFrame v2 = new VentanaGestionGestorMantenimiento(administradorGeneral);
        v2.setVisible(true);
    }//GEN-LAST:event_btnGestionGestorMouseClicked

    private void btnGestionGestorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionGestorMouseEntered
        panelGestMant.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnGestionGestorMouseEntered

    private void btnGestionGestorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionGestorMouseExited
        panelGestMant.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnGestionGestorMouseExited

    private void btnGestionAerolineasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAerolineasMouseEntered
        panelGestAero.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnGestionAerolineasMouseEntered

    private void btnGestionAerolineasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAerolineasMouseExited
        panelGestAero.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnGestionAerolineasMouseExited

    private void btnSolicitudesMantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMantenimientoMouseEntered
        panelAtender.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnSolicitudesMantenimientoMouseEntered

    private void btnSolicitudesMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMantenimientoMouseExited
        panelAtender.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnSolicitudesMantenimientoMouseExited

    private void btnGestionAerolineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAerolineasMouseClicked
        this.dispose();
        JFrame v2 = new VentanaGestionAerolinea(administradorGeneral);
        v2.setVisible(true);
    }//GEN-LAST:event_btnGestionAerolineasMouseClicked

    private void btnGestionAdminAeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAdminAeroMouseClicked
        this.dispose();
        JFrame v2 = new VentanaSeleccionarAerolinea(administradorGeneral);
        v2.setVisible(true);
    }//GEN-LAST:event_btnGestionAdminAeroMouseClicked

    private void btnGestionAdminAeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAdminAeroMouseEntered
        panelGestuAdmin.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnGestionAdminAeroMouseEntered

    private void btnGestionAdminAeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAdminAeroMouseExited
        panelGestuAdmin.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnGestionAdminAeroMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGestionAdminAero;
    private javax.swing.JLabel btnGestionAerolineas;
    private javax.swing.JLabel btnGestionGestor;
    private javax.swing.JMenu btnRegresar;
    private javax.swing.JLabel btnSolicitudesMantenimiento;
    private javax.swing.JMenu btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel panelAtender;
    private javax.swing.JPanel panelGestAero;
    private javax.swing.JPanel panelGestMant;
    private javax.swing.JPanel panelGestuAdmin;
    // End of variables declaration//GEN-END:variables
}
