package VistasAdminGeneral;

import Controladores.ControladorVentanaGestionAdministradoresAerolinea;
import Excepciones.*;
import Modelos.AdministradorAerolinea;
import Modelos.Aerolinea;
import Modelos.Persona;
import Util.LSE;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diaza
 */
public class VentanaGestionAdministradoresAerolineas extends javax.swing.JFrame {

    private Persona administradorGeneral;
    private ControladorVentanaGestionAdministradoresAerolinea controlador;
    DefaultTableModel modelo;
    Date hoy = new Date();
    LocalDate fecha = new  java.sql.Date(hoy.getTime()).toLocalDate();

        
    /**
     * Creates new form VentanaGestionAdministradoresAerolineas
     */
    public VentanaGestionAdministradoresAerolineas(Persona adminGeneral) {
        initComponents();
        this.administradorGeneral = adminGeneral;
        this.controlador = new ControladorVentanaGestionAdministradoresAerolinea();
        modelo = (DefaultTableModel)tabla.getModel();
        txtFechaRegistro.setText(fecha.toString());
        actualizarTabla();
        actualizarComboBox();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cboGenero = new javax.swing.JComboBox<>();
        txtFechaRegistro = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        txtConfirmarContrasenia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cboAerolinea = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        panelBuscar2 = new javax.swing.JPanel();
        btnBuscar2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelEditar2 = new javax.swing.JPanel();
        btnEditar2 = new javax.swing.JLabel();
        panelLimpiar = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JLabel();
        panelEliminar1 = new javax.swing.JPanel();
        btnEliminar1 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVolver = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(65, 92, 117));
        jLabel4.setText("Confirme su contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabel5.setForeground(new java.awt.Color(65, 92, 117));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(65, 92, 117));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel9.setForeground(new java.awt.Color(65, 92, 117));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Identificación");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 80, -1));

        jLabel10.setForeground(new java.awt.Color(65, 92, 117));
        jLabel10.setText("Fecha registro");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, -1));

        jLabel11.setForeground(new java.awt.Color(65, 92, 117));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Télefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, -1));

        jLabel13.setForeground(new java.awt.Color(65, 92, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Usuario ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 50, -1));

        jLabel8.setForeground(new java.awt.Color(65, 92, 117));
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel12.setForeground(new java.awt.Color(65, 92, 117));
        jLabel12.setText("Género");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, -1));

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Femenino" }));
        jPanel1.add(cboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 120, -1));

        txtFechaRegistro.setEditable(false);
        jPanel1.add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 120, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 120, -1));
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, -1));
        jPanel1.add(txtConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 120, -1));

        jLabel15.setForeground(new java.awt.Color(65, 92, 117));
        jLabel15.setText("Apellidos");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 92, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Administrador Aerolinea");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 310, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(65, 92, 117));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Registrar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 10));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setForeground(new java.awt.Color(65, 92, 117));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "AdminAero", "Pais", "Codigo", "Nombre Aero", "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionBackground(new java.awt.Color(65, 92, 117));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 610, 290));

        jLabel7.setForeground(new java.awt.Color(65, 92, 117));
        jLabel7.setText("Nombres");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel1.add(cboAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(65, 92, 117));
        jLabel16.setText("Seleccione una aerolinea");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(65, 92, 117));
        jLabel18.setText("Información del administrador Aerolínea");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(65, 92, 117));
        jLabel19.setText("Ingrese un id para buscar:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 30));

        txtIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 130, 30));

        panelBuscar2.setBackground(new java.awt.Color(65, 92, 117));

        btnBuscar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar2.setText("Buscar");
        btnBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBuscar2Layout = new javax.swing.GroupLayout(panelBuscar2);
        panelBuscar2.setLayout(panelBuscar2Layout);
        panelBuscar2Layout.setHorizontalGroup(
            panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelBuscar2Layout.setVerticalGroup(
            panelBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(65, 92, 117));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Lista Administradores de aerolinea");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 200, 20));

        panelEditar2.setBackground(new java.awt.Color(65, 92, 117));

        btnEditar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar2.setText("Editar");
        btnEditar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditar2Layout = new javax.swing.GroupLayout(panelEditar2);
        panelEditar2.setLayout(panelEditar2Layout);
        panelEditar2Layout.setHorizontalGroup(
            panelEditar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEditar2Layout.setVerticalGroup(
            panelEditar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 130, 30));

        panelLimpiar.setBackground(new java.awt.Color(65, 92, 117));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLimpiarLayout = new javax.swing.GroupLayout(panelLimpiar);
        panelLimpiar.setLayout(panelLimpiarLayout);
        panelLimpiarLayout.setHorizontalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelLimpiarLayout.setVerticalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 140, -1));

        panelEliminar1.setBackground(new java.awt.Color(65, 92, 117));

        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEliminar1Layout = new javax.swing.GroupLayout(panelEliminar1);
        panelEliminar1.setLayout(panelEliminar1Layout);
        panelEliminar1Layout.setHorizontalGroup(
            panelEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEliminar1Layout.setVerticalGroup(
            panelEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        panelRegistro.setBackground(new java.awt.Color(65, 92, 117));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 190, 30));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver.setText("Mas opciones");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnVolver.add(btnRegresar);

        jMenuBar1.add(btnVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuPrincipalAdmGeneral(administradorGeneral);
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnBuscar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar2MouseClicked
        if(txtIdBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el numero de identificación que desea buscar");
            return;
        }else {
            String identificacion = txtIdBuscar.getText();
            AdministradorAerolinea administradorAerolinea = (AdministradorAerolinea) controlador.buscarAdminAerolineaId(identificacion);
            Aerolinea aerolineaBuscada = controlador.buscarAdAerolinea(identificacion);
            if(administradorAerolinea != null) {
                txtNombres.setText(administradorAerolinea.getNombres());
                txtApellidos.setText(administradorAerolinea.getApellidos());
                txtEdad.setText(String.valueOf(administradorAerolinea.getEdad()));
                txtIdentificacion.setText(administradorAerolinea.getIdentificacion());
                cboGenero.setSelectedItem(administradorAerolinea.getGenero());
                cboAerolinea.setSelectedItem(aerolineaBuscada.getNombreAerolinea());
                txtCorreo.setText(administradorAerolinea.getCorreo());
                txtFechaRegistro.setText(administradorAerolinea.getFechaContratación().toString());
                txtContrasenia.setText(administradorAerolinea.getContrasenia());
                txtConfirmarContrasenia.setText(administradorAerolinea.getContrasenia());
                txtTelefono.setText(administradorAerolinea.getNumTelefono());
            } else {
                JOptionPane.showMessageDialog(null, "El Administrador de aerolinea con numero de identificación: " + identificacion + "\n no se encuentra registrado");
            }
        }
    }//GEN-LAST:event_btnBuscar2MouseClicked

    private void btnBuscar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar2MouseEntered
        panelBuscar2.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnBuscar2MouseEntered

    private void btnBuscar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar2MouseExited
        panelBuscar2.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnBuscar2MouseExited

    private void btnEditar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseClicked

        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || txtFechaRegistro.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {

            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();
            AdministradorAerolinea administradorAerolinea = new AdministradorAerolinea(fecha, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Administrador Aerolinea");
            
            try{
                controlador.editarAdministrador(administradorAerolinea);
                JOptionPane.showMessageDialog(null, "La informacion del Administrador de aerolinea: " +nombres +" "+apellidos +  "\n ha sido actualizada");
                limpiarCampos();
                actualizarTabla();
            }catch(CambioCorreoIdentificacionException | IdentificacionNoExisteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                actualizarTabla();
            }
        }
    }//GEN-LAST:event_btnEditar2MouseClicked

    private void btnEditar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseEntered
        panelEditar2.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEditar2MouseEntered

    private void btnEditar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseExited
        panelEditar2.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEditar2MouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        panelLimpiar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        panelLimpiar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseClicked
        if (txtIdBuscar.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese un numero de identificación para buscar un Administrador y eliminarlo del sistema");
            return;
        }else {
            String identificacion = txtIdBuscar.getText();
            Aerolinea aerolinea = controlador.buscarAdAerolinea(identificacion);
            try{
                controlador.eliminarAdministradorAero(identificacion, aerolinea);
                JOptionPane.showMessageDialog(null, "Administrador de eliminado correctamente");
                limpiarCampos();
                actualizarTabla();
            }catch(Almenos1AdminException | IdentificacionNoExisteException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminar1MouseClicked

    private void btnEliminar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseEntered
        panelEliminar1.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEliminar1MouseEntered

    private void btnEliminar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseExited
        panelEliminar1.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEliminar1MouseExited

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || cboAerolinea.getSelectedIndex() == 0 || txtFechaRegistro.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else if(cboAerolinea.getSelectedIndex() == 0 ){
                JOptionPane.showMessageDialog(null, "Seleccione una Aerolinea para registrar al Administrador");
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String telefono = txtTelefono.getText();
            String fechaRegistro = txtFechaRegistro.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();
            String aerolineaSeleccionada = String.valueOf(cboAerolinea.getSelectedItem());
            Aerolinea aerolinea = controlador.buscarAeroNombre(aerolineaSeleccionada);
            AdministradorAerolinea administradorAerolinea = new AdministradorAerolinea(fecha, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Administrador Aerolinea");
            Aerolinea aerolineaGuardar = new Aerolinea(aerolinea.getNombreAerolinea(), aerolinea.getCodigoAerolinea(), aerolinea.getPais(), aerolinea.getListaAviones(), controlador.obtenerListaEmpleados(aerolinea.getCodigoAerolinea()));
            
            try{
                controlador.guardarAerolinea(aerolinea, administradorAerolinea);
                JOptionPane.showMessageDialog(null, "Se registró correctamente la aerolinea " + aerolineaGuardar.getNombreAerolinea() + "\n con Administrador de Aerolinea: " + nombres + " " + apellidos);
                limpiarCampos();
                actualizarTabla();
            }catch (CodigoAerolineaExisteException | CorreoRegistradoException | AdminAeroRegistradoException | GestorRegistradoException | CapitanVueloRegistradoException | EmpleadoLogisticaRegistradoException | InformacionViajeroException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        panelRegistro.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        panelRegistro.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int row = tabla.getSelectedRow();
        txtIdentificacion.setText(modelo.getValueAt(row,0).toString());

        String identificacion = txtIdentificacion.getText();
        AdministradorAerolinea administradorAerolinea = (AdministradorAerolinea) controlador.buscarAdminAerolineaId(identificacion);
        Aerolinea aerolineaBuscada = controlador.buscarAdAerolinea(identificacion);

        txtNombres.setText(administradorAerolinea.getNombres());
        txtApellidos.setText(administradorAerolinea.getApellidos());
        txtEdad.setText(String.valueOf(administradorAerolinea.getEdad()));
        txtIdentificacion.setText(administradorAerolinea.getIdentificacion());
        txtIdBuscar.setText(administradorAerolinea.getIdentificacion());
        txtTelefono.setText(administradorAerolinea.getNumTelefono());
        cboGenero.setSelectedItem(administradorAerolinea.getGenero());
        cboAerolinea.setSelectedItem(aerolineaBuscada.getNombreAerolinea());
        txtFechaRegistro.setText(administradorAerolinea.getFechaContratación().toString());
        txtCorreo.setText(administradorAerolinea.getCorreo());
        txtContrasenia.setText(administradorAerolinea.getContrasenia());
        txtConfirmarContrasenia.setText(administradorAerolinea.getContrasenia());
    }//GEN-LAST:event_tablaMouseClicked

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtEdad.getText().trim().length() == 2){
            evt.consume();
        }  
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtIdentificacion.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtTelefono.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtIdBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdBuscarKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtIdBuscar.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtIdBuscarKeyTyped

    public void actualizarComboBox() {
        cboAerolinea.removeAllItems();
        LSE<String> lista = new LSE<>();

        try {
            LSE<Aerolinea> listaAerolineas = controlador.traerAerolineas();
            for (int i = 0; i < listaAerolineas.size(); i++) {
                Aerolinea aerlineas = listaAerolineas.get(i);
                String nombres = aerlineas.getNombreAerolinea();
                lista.add(nombres);
            }
            cboAerolinea.addItem("-Seleccionar-");
            for (int i = 0; i < lista.size(); i++) {
                String item = lista.get(i);
                cboAerolinea.addItem(item);
            }
        } catch (Exception e) {
        }
    }
     
    public void limpiarCampos() {
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtEdad.setText(null);
        txtIdentificacion.setText(null);
        cboGenero.setSelectedIndex(0);
        txtTelefono.setText(null);
        txtCorreo.setText(null);
        txtContrasenia.setText(null);
        txtConfirmarContrasenia.setText(null);
        cboAerolinea.setSelectedIndex(0);
    }
    
    private void actualizarTabla(){
        LSE<AdministradorAerolinea> administradores = controlador.obtenerAdministradoresDeAerolineas();
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }   
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < administradores.size() ; i++) {
                    AdministradorAerolinea aux = administradores.get(i); 
                    Aerolinea aerolinea = controlador.buscarAdAerolinea(aux.getIdentificacion());
                    Object[] ob = {aux.getIdentificacion(), aux.getNombres() + " " + aux.getApellidos(), aerolinea.getPais(), aerolinea.getCodigoAerolinea(), aerolinea.getNombreAerolinea(), aux.getCorreo(), aux.getContrasenia()};
                    modelo.addRow(ob);                    
                }
            }catch(NullPointerException e){        
            }
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar2;
    private javax.swing.JLabel btnEditar2;
    private javax.swing.JLabel btnEliminar1;
    private javax.swing.JLabel btnLimpiar;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JMenu btnRegresar;
    private javax.swing.JMenu btnVolver;
    private javax.swing.JComboBox<String> cboAerolinea;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBuscar2;
    private javax.swing.JPanel panelEditar2;
    private javax.swing.JPanel panelEliminar1;
    private javax.swing.JPanel panelLimpiar;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtConfirmarContrasenia;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
