package VistasAdminGeneral;

import Controladores.ControladorVentanaGestionAdministradoresAerolinea;
import Excepciones.*;
import Modelos.AdministradorAerolinea;
import Modelos.Aerolinea;
import Modelos.Persona;
import Util.LSE;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diaza
 */
public class VentanaSeleccionarAerolinea extends javax.swing.JFrame {

    private ControladorVentanaGestionAdministradoresAerolinea controlador;
    DefaultTableModel modelo;
    Date hoy = new Date();
    LocalDate fecha = new  java.sql.Date(hoy.getTime()).toLocalDate();

        
    /**
     * Creates new form VentanaGestionAdministradoresAerolineas
     */
    public VentanaSeleccionarAerolinea() {
        initComponents();
        this.controlador = new ControladorVentanaGestionAdministradoresAerolinea();
        modelo = (DefaultTableModel)tabla.getModel();
        txtFechaRegistro.setText(fecha.toString());
        actualizarComboBox();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cboGenero = new javax.swing.JComboBox<>();
        txtFechaRegistro = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        txtConfirmarContrasenia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cboAerolinea = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelEditar2 = new javax.swing.JPanel();
        btnEditar2 = new javax.swing.JLabel();
        panelLimpiar = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JLabel();
        panelEliminar1 = new javax.swing.JPanel();
        btnEliminar1 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPaisAerolinea = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNombreAerolinea = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEditarAerolinea = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEliminarAerolinea = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCodigoAerolinea = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVolver = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(65, 92, 117));
        jLabel4.setText("Confirme su contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(65, 92, 117));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(65, 92, 117));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel9.setForeground(new java.awt.Color(65, 92, 117));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Identificación");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 80, -1));

        jLabel10.setForeground(new java.awt.Color(65, 92, 117));
        jLabel10.setText("Fecha registro");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 110, -1));

        jLabel11.setForeground(new java.awt.Color(65, 92, 117));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Télefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 60, -1));

        jLabel13.setForeground(new java.awt.Color(65, 92, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Usuario ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 50, -1));

        jLabel8.setForeground(new java.awt.Color(65, 92, 117));
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jLabel12.setForeground(new java.awt.Color(65, 92, 117));
        jLabel12.setText("Género");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 120, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 120, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, -1));

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Femenino" }));
        jPanel1.add(cboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));

        txtFechaRegistro.setEditable(false);
        jPanel1.add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 120, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 120, -1));
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, -1));
        jPanel1.add(txtConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 120, -1));

        jLabel15.setForeground(new java.awt.Color(65, 92, 117));
        jLabel15.setText("Apellidos");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 92, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Aerolíneas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(65, 92, 117));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Gestionar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 10));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setForeground(new java.awt.Color(65, 92, 117));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "AdminAero", "Edad", "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionBackground(new java.awt.Color(65, 92, 117));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 610, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pais");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        cboAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAerolineaActionPerformed(evt);
            }
        });
        jPanel1.add(cboAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(65, 92, 117));
        jLabel16.setText("Seleccione una aerolinea");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Información de la Aerolínea");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(65, 92, 117));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Lista Administradores de aerolinea");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 200, 20));

        panelEditar2.setBackground(new java.awt.Color(65, 92, 117));

        btnEditar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar2.setText("Editar");
        btnEditar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditar2Layout = new javax.swing.GroupLayout(panelEditar2);
        panelEditar2.setLayout(panelEditar2Layout);
        panelEditar2Layout.setHorizontalGroup(
            panelEditar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEditar2Layout.setVerticalGroup(
            panelEditar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 130, 30));

        panelLimpiar.setBackground(new java.awt.Color(65, 92, 117));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLimpiarLayout = new javax.swing.GroupLayout(panelLimpiar);
        panelLimpiar.setLayout(panelLimpiarLayout);
        panelLimpiarLayout.setHorizontalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelLimpiarLayout.setVerticalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 140, -1));

        panelEliminar1.setBackground(new java.awt.Color(65, 92, 117));

        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEliminar1Layout = new javax.swing.GroupLayout(panelEliminar1);
        panelEliminar1.setLayout(panelEliminar1Layout);
        panelEliminar1Layout.setHorizontalGroup(
            panelEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEliminar1Layout.setVerticalGroup(
            panelEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));

        panelRegistro.setBackground(new java.awt.Color(65, 92, 117));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 140, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(65, 92, 117));
        jLabel19.setText("Registrar nuevo administrador Aerolínea");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 40));

        jLabel20.setForeground(new java.awt.Color(65, 92, 117));
        jLabel20.setText("Nombres");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));
        jPanel1.add(txtPaisAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 270, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nombre");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(txtNombreAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Código");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnEditarAerolinea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarAerolinea.setForeground(new java.awt.Color(65, 92, 117));
        btnEditarAerolinea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditarAerolinea.setText("Editar");
        btnEditarAerolinea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarAerolinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarAerolineaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 120, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarAerolinea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarAerolinea.setForeground(new java.awt.Color(65, 92, 117));
        btnEliminarAerolinea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarAerolinea.setText("Eliminar");
        btnEliminarAerolinea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 120, -1));

        jPanel4.setBackground(new java.awt.Color(65, 92, 117));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoAerolinea.setEditable(false);
        jPanel4.add(txtCodigoAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 147, 270, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 330));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aleta.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 70, 70));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver.setText("Mas opciones");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnVolver.add(btnRegresar);

        jMenuBar1.add(btnVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuPrincipalAdmGeneral();
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnEditar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseClicked

        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || txtFechaRegistro.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {

            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();
            AdministradorAerolinea administradorAerolinea = new AdministradorAerolinea(fecha, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Administrador Aerolinea");
            int codigo = Integer.parseInt(txtCodigoAerolinea.getText());
            
            try{
                controlador.editarAdministrador(administradorAerolinea);
                JOptionPane.showMessageDialog(null, "La informacion del Administrador de aerolinea: " +nombres +" "+apellidos +  "\n ha sido actualizada");
                limpiarCampos();
                actualizarTabla(codigo);
            }catch(CambioCorreoIdentificacionException | IdentificacionNoExisteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                actualizarTabla(codigo);
            }
        }
    }//GEN-LAST:event_btnEditar2MouseClicked

    private void btnEditar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseEntered
        panelEditar2.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEditar2MouseEntered

    private void btnEditar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar2MouseExited
        panelEditar2.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEditar2MouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        panelLimpiar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        panelLimpiar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseClicked
        if (txtIdentificacion.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese un numero de identificación para buscar un Administrador y eliminarlo del sistema");
            return;
        }else {
            String identificacion = txtIdentificacion.getText();
            Aerolinea aerolinea = controlador.buscarAdAerolinea(identificacion);
            try{
                controlador.eliminarAdministradorAero(identificacion, aerolinea);
                JOptionPane.showMessageDialog(null, "Administrador de eliminado correctamente");
                limpiarCampos();
                actualizarTabla(aerolinea.getCodigoAerolinea());
            }catch(Almenos1AdminException | IdentificacionNoExisteException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminar1MouseClicked

    private void btnEliminar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseEntered
        panelEliminar1.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEliminar1MouseEntered

    private void btnEliminar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseExited
        panelEliminar1.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEliminar1MouseExited

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || cboAerolinea.getSelectedIndex() == 0 || txtFechaRegistro.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else if(cboAerolinea.getSelectedIndex() == 0 ){
                JOptionPane.showMessageDialog(null, "Seleccione una Aerolinea para registrar al Administrador");
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String telefono = txtTelefono.getText();
            String fechaRegistro = txtFechaRegistro.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();
            String aerolineaSeleccionada = String.valueOf(cboAerolinea.getSelectedItem());
            Aerolinea aerolinea = controlador.buscarAerolineaNombre(aerolineaSeleccionada);
            AdministradorAerolinea administradorAerolinea = new AdministradorAerolinea(fecha, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Administrador Aerolinea");
            Aerolinea aerolineaGuardar = new Aerolinea(aerolinea.getNombreAerolinea(), aerolinea.getCodigoAerolinea(), aerolinea.getPais(), aerolinea.getListaAviones(), controlador.obtenerListaEmpleados(aerolinea.getCodigoAerolinea()));
            
            try{
                controlador.guardarAerolinea(aerolinea, administradorAerolinea);
                JOptionPane.showMessageDialog(null, "Se registró correctamente la aerolinea " + aerolineaGuardar.getNombreAerolinea() + "\n con Administrador de Aerolinea: " + nombres + " " + apellidos);
                limpiarCampos();
                actualizarTabla(aerolineaGuardar.getCodigoAerolinea());
            }catch (CodigoAerolineaExisteException | CorreoRegistradoException | AdminAeroRegistradoException | GestorRegistradoException | CapitanVueloRegistradoException | EmpleadoLogisticaRegistradoException | InformacionViajeroException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        panelRegistro.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        panelRegistro.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int row = tabla.getSelectedRow();
        txtIdentificacion.setText(modelo.getValueAt(row,0).toString());

        String identificacion = txtIdentificacion.getText();
        AdministradorAerolinea administradorAerolinea = (AdministradorAerolinea) controlador.buscarAdminAerolineaId(identificacion);
        Aerolinea aerolineaBuscada = controlador.buscarAdAerolinea(identificacion);

        txtNombres.setText(administradorAerolinea.getNombres());
        txtApellidos.setText(administradorAerolinea.getApellidos());
        txtEdad.setText(String.valueOf(administradorAerolinea.getEdad()));
        txtIdentificacion.setText(administradorAerolinea.getIdentificacion());
        txtTelefono.setText(administradorAerolinea.getNumTelefono());
        cboGenero.setSelectedItem(administradorAerolinea.getGenero());
        cboAerolinea.setSelectedItem(aerolineaBuscada.getNombreAerolinea());
        txtFechaRegistro.setText(administradorAerolinea.getFechaContratación().toString());
        txtCorreo.setText(administradorAerolinea.getCorreo());
        txtContrasenia.setText(administradorAerolinea.getContrasenia());
        txtConfirmarContrasenia.setText(administradorAerolinea.getContrasenia());
    }//GEN-LAST:event_tablaMouseClicked

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtEdad.getText().trim().length() == 2){
            evt.consume();
        }  
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtIdentificacion.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtTelefono.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void cboAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAerolineaActionPerformed
        String nombre = (String) cboAerolinea.getSelectedItem();
        if(nombre.equals("-Seleccionar-")){
            modelo.setRowCount(0);
            limpiarCampos();
        }else {
            Aerolinea aerolineaBuscada = controlador.buscarAerolineaNombre(nombre);
            txtNombreAerolinea.setText(aerolineaBuscada.getNombreAerolinea());
            txtCodigoAerolinea.setText(String.valueOf(aerolineaBuscada.getCodigoAerolinea()));
            txtPaisAerolinea.setText(aerolineaBuscada.getPais());
            actualizarTabla(aerolineaBuscada.getCodigoAerolinea());
        }
    }//GEN-LAST:event_cboAerolineaActionPerformed

    private void btnEditarAerolineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarAerolineaMouseClicked
        if(txtNombreAerolinea.getText().isEmpty() || txtCodigoAerolinea.getText().isEmpty() || txtPaisAerolinea.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Existen campos obligatorios por llenar");
        }else {
            String nombre = txtNombreAerolinea.getText();
            int codigo = Integer.parseInt(txtCodigoAerolinea.getText());
            String pais = txtPaisAerolinea.getText();
            
            
        }
    }//GEN-LAST:event_btnEditarAerolineaMouseClicked

    public void actualizarComboBox() {
        cboAerolinea.removeAllItems();
        LSE<String> lista = new LSE<>();

        try {
            LSE<Aerolinea> listaAerolineas = controlador.traerAerolineas();
            for (int i = 0; i < listaAerolineas.size(); i++) {
                Aerolinea aerlineas = listaAerolineas.get(i);
                String nombres = aerlineas.getNombreAerolinea();
                lista.add(nombres);
            }
            cboAerolinea.addItem("-Seleccionar-");
            for (int i = 0; i < lista.size(); i++) {
                String item = lista.get(i);
                cboAerolinea.addItem(item);
            }
        } catch (Exception e) {
        }
    }
     
    public void limpiarCampos() {
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtEdad.setText(null);
        txtIdentificacion.setText(null);
        cboGenero.setSelectedIndex(0);
        txtTelefono.setText(null);
        txtCorreo.setText(null);
        txtContrasenia.setText(null);
        txtConfirmarContrasenia.setText(null);
        txtCodigoAerolinea.setText(null);
        txtNombreAerolinea.setText(null);
        txtPaisAerolinea.setText(null);
        cboAerolinea.setSelectedIndex(0);
    }
    
    private void actualizarTabla(int codigo){
        LSE<AdministradorAerolinea> administradores = controlador.obtenerAdministradoresDeAerolineas(codigo);
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }   
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < administradores.size() ; i++) {
                    AdministradorAerolinea aux = administradores.get(i); 
                    Aerolinea aerolinea = controlador.buscarAdAerolinea(aux.getIdentificacion());
                    Object[] ob = {aux.getIdentificacion(), aux.getNombres() + " " + aux.getApellidos(), aux.getEdad(), aux.getCorreo(), aux.getContrasenia()};
                    modelo.addRow(ob);                    
                }
            }catch(NullPointerException e){        
            }
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEditar2;
    private javax.swing.JLabel btnEditarAerolinea;
    private javax.swing.JLabel btnEliminar1;
    private javax.swing.JLabel btnEliminarAerolinea;
    private javax.swing.JLabel btnLimpiar;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JMenu btnRegresar;
    private javax.swing.JMenu btnVolver;
    private javax.swing.JComboBox<String> cboAerolinea;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelEditar2;
    private javax.swing.JPanel panelEliminar1;
    private javax.swing.JPanel panelLimpiar;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigoAerolinea;
    private javax.swing.JTextField txtConfirmarContrasenia;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombreAerolinea;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPaisAerolinea;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
