package VistasAdminAerolinea;

import Controladores.ControladorVentanaGestionEmpleadoLogistica;
import Excepciones.*;
import Modelos.*;
import Util.LSE;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diaza
 */
public class VentanaGestionEmpleadoLogistica extends javax.swing.JFrame {

    private AdministradorAerolinea administradorAerolinea;
    private Aerolinea aerolineaRecibida;
    DefaultTableModel modelo;
    private ControladorVentanaGestionEmpleadoLogistica controlador;
    
    /**
     * Creates new form VentanaGestionEmpleadoLogistica
     */
    public VentanaGestionEmpleadoLogistica(AdministradorAerolinea adminAerolinea, Aerolinea aerolinea) {
        initComponents();
        this.administradorAerolinea = adminAerolinea; 
        this.aerolineaRecibida = aerolinea;
        modelo = (DefaultTableModel)tabla.getModel();
        this.controlador = new ControladorVentanaGestionEmpleadoLogistica(aerolinea);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel20 = new javax.swing.JPanel();
        btnCrearCuenta = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cboGenero = new javax.swing.JComboBox<>();
        txtTarjetaProfesional = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        txtConfirmarContrasenia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtIdBuscar = new javax.swing.JTextField();
        panelBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JLabel();
        panelLimpiar = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAniosExperiencia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtRutasAsignadas = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVolver3 = new javax.swing.JMenu();
        btnRegresar3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(65, 92, 117));
        jLabel4.setText("Confirme su contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jLabel5.setForeground(new java.awt.Color(65, 92, 117));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 70, -1));

        jLabel6.setForeground(new java.awt.Color(65, 92, 117));
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel9.setForeground(new java.awt.Color(65, 92, 117));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Identificación");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 80, -1));

        jLabel10.setForeground(new java.awt.Color(65, 92, 117));
        jLabel10.setText("Rutas asignadas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        jLabel11.setForeground(new java.awt.Color(65, 92, 117));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Télefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, -1));

        jLabel13.setForeground(new java.awt.Color(65, 92, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Usuario ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, -1));

        jLabel8.setForeground(new java.awt.Color(65, 92, 117));
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setForeground(new java.awt.Color(65, 92, 117));
        jLabel12.setText("Género");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        panel20.setBackground(new java.awt.Color(65, 92, 117));

        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearCuenta.setText("Registro");
        btnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel20Layout = new javax.swing.GroupLayout(panel20);
        panel20.setLayout(panel20Layout);
        panel20Layout.setHorizontalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel20Layout.setVerticalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 270, 30));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, -1));

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Femenino" }));
        jPanel1.add(cboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 120, -1));

        txtTarjetaProfesional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarjetaProfesionalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarjetaProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 120, -1));
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 120, -1));
        jPanel1.add(txtConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 92, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Empleado Logistica");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(65, 92, 117));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Registrar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 270, 10));

        jLabel15.setForeground(new java.awt.Color(65, 92, 117));
        jLabel15.setText("Apellidos");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel17.setForeground(new java.awt.Color(65, 92, 117));
        jLabel17.setText("N° Tarjeta profesional");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(65, 92, 117));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Lista EmpleadoLogistica");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 190, 20));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setForeground(new java.awt.Color(65, 92, 117));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellidos", "Id", "Género", "Años Experiencia", "Tarjeta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionBackground(new java.awt.Color(65, 92, 117));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 500, 280));

        txtIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, 30));

        panelBuscar.setBackground(new java.awt.Color(65, 92, 117));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 120, 30));

        panelEditar.setBackground(new java.awt.Color(65, 92, 117));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 130, 30));

        panelLimpiar.setBackground(new java.awt.Color(65, 92, 117));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLimpiarLayout = new javax.swing.GroupLayout(panelLimpiar);
        panelLimpiar.setLayout(panelLimpiarLayout);
        panelLimpiarLayout.setHorizontalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelLimpiarLayout.setVerticalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 140, -1));

        panelEliminar.setBackground(new java.awt.Color(65, 92, 117));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(65, 92, 117));
        jLabel16.setText("Ingrese un id para buscar:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 30));

        txtAniosExperiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAniosExperienciaKeyTyped(evt);
            }
        });
        jPanel1.add(txtAniosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, -1));

        jLabel18.setForeground(new java.awt.Color(65, 92, 117));
        jLabel18.setText("Años experiencia");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, -1));
        jPanel1.add(txtRutasAsignadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver3.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver3.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver3.setText("Mas opciones");
        btnVolver3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolver3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolver3MouseReleased(evt);
            }
        });

        btnRegresar3.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar3.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar3.setText("Volver");
        btnRegresar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresar3MouseExited(evt);
            }
        });
        btnVolver3.add(btnRegresar3);

        jMenuBar1.add(btnVolver3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar3MouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuPrincipalAdAerolinea(administradorAerolinea, aerolineaRecibida);
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresar3MouseClicked

    private void btnRegresar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar3MouseEntered
        btnRegresar3.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresar3MouseEntered

    private void btnRegresar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar3MouseExited
        btnRegresar3.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresar3MouseExited

    private void btnVolver3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver3MousePressed
        btnVolver3.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolver3MousePressed

    private void btnVolver3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver3MouseReleased
        btnVolver3.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolver3MouseReleased

    private void btnCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseClicked
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || txtAniosExperiencia.getText().isEmpty() || txtTarjetaProfesional.getText().isEmpty() || txtRutasAsignadas.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String rutasAsignadas = txtRutasAsignadas.getText();
            int aniosExperiencia = Integer.parseInt(txtAniosExperiencia.getText());
            String telefono = txtTelefono.getText();
            String tarjetaProfesional = txtTarjetaProfesional.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();

            EmpleadoLogistica empleadoLogistica = new EmpleadoLogistica(tarjetaProfesional, aniosExperiencia, rutasAsignadas, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Empleado Logistica");

            try{
                controlador.guardarEmpleadoLog(empleadoLogistica);
                JOptionPane.showMessageDialog(null, "Se registró correctamente el Empleado de Logistica: " + nombres + " " + apellidos + "\n con identificación número: " + identificacion);
                limpiarCampos();
                actualizarTabla();
            }catch (EmpleadoLogisticaRegistradoException | CorreoRegistradoException | GestorRegistradoException | AdminAeroRegistradoException | CapitanVueloRegistradoException | InformacionViajeroException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCrearCuentaMouseClicked

    private void btnCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseEntered
        panel20.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnCrearCuentaMouseEntered

    private void btnCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaMouseExited
        panel20.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnCrearCuentaMouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int row = tabla.getSelectedRow();
        txtIdentificacion.setText(modelo.getValueAt(row,2).toString());

        String identificacion = txtIdentificacion.getText();
        EmpleadoLogistica empleadoLogistica = (EmpleadoLogistica) controlador.buscarEmpleadoLogistica(identificacion);

        txtNombres.setText(empleadoLogistica.getNombres());
        txtApellidos.setText(empleadoLogistica.getApellidos());
        txtEdad.setText(String.valueOf(empleadoLogistica.getEdad()));
        txtIdentificacion.setText(empleadoLogistica.getIdentificacion());
        txtTelefono.setText(empleadoLogistica.getNumTelefono());
        cboGenero.setSelectedItem(empleadoLogistica.getGenero());
        txtTarjetaProfesional.setText(empleadoLogistica.getNumeroTarjetaProfesional());
        txtAniosExperiencia.setText(String.valueOf(empleadoLogistica.getAniosExperiencia()));
        txtRutasAsignadas.setText(empleadoLogistica.getRutasAsignadas());
        txtCorreo.setText(empleadoLogistica.getCorreo());
        txtContrasenia.setText(empleadoLogistica.getContrasenia());
        txtConfirmarContrasenia.setText(empleadoLogistica.getContrasenia());

    }//GEN-LAST:event_tablaMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        if(txtIdBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el numero de identificación que desea buscar");
            return;
        }else {
            String identificacion = txtIdBuscar.getText();
            EmpleadoLogistica empleadoLogistica = (EmpleadoLogistica) controlador.buscarEmpleadoLogistica(identificacion);
            if(empleadoLogistica != null) {
                txtNombres.setText(empleadoLogistica.getNombres());
                txtApellidos.setText(empleadoLogistica.getApellidos());
                txtEdad.setText(String.valueOf(empleadoLogistica.getEdad()));
                txtIdentificacion.setText(empleadoLogistica.getIdentificacion());
                cboGenero.setSelectedItem(empleadoLogistica.getGenero());
                txtCorreo.setText(empleadoLogistica.getCorreo());
                txtTarjetaProfesional.setText(empleadoLogistica.getNumeroTarjetaProfesional());
                txtAniosExperiencia.setText(String.valueOf(empleadoLogistica.getAniosExperiencia()));
                txtRutasAsignadas.setText(empleadoLogistica.getRutasAsignadas());
                txtContrasenia.setText(empleadoLogistica.getContrasenia());
                txtConfirmarContrasenia.setText(empleadoLogistica.getContrasenia());
                txtTelefono.setText(empleadoLogistica.getNumTelefono());
            }else {
                JOptionPane.showMessageDialog(null, "El Empleado de logistica con numero de identificación: " + identificacion + "\n no se encuentra registrado");
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        panelBuscar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        panelBuscar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || txtAniosExperiencia.getText().isEmpty() || txtTarjetaProfesional.getText().isEmpty() || txtRutasAsignadas.getText().isEmpty() || txtContrasenia.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty() || !txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
            if(!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())){
                JOptionPane.showMessageDialog( null , "Las contraseñas NO coinciden");
                return;
            }else {
                JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
                return;
            }
        }else {
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String identificacion = txtIdentificacion.getText();
            String genero = String.valueOf(cboGenero.getSelectedItem());
            String rutasAsignadas = txtRutasAsignadas.getText();
            int aniosExperiencia = Integer.parseInt(txtAniosExperiencia.getText());
            String telefono = txtTelefono.getText();
            String tarjetaProfesional = txtTarjetaProfesional.getText();
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();

            EmpleadoLogistica empleadoLogistica = new EmpleadoLogistica(tarjetaProfesional, aniosExperiencia, rutasAsignadas, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, "Empleado Logistica");

            try{
                controlador.editarEmpleadoLog(empleadoLogistica);
                JOptionPane.showMessageDialog(null, "La informacion del Empleado de logistica: " +nombres +" "+apellidos +  "\n ha sido actualizada");
                limpiarCampos();
                actualizarTabla();
            }catch(CambioCorreoIdentificacionException | IdentificacionNoExisteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                actualizarTabla();
            }
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        panelEditar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        panelEditar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        panelLimpiar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        panelLimpiar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (txtIdBuscar.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese un numero de identificación para buscar un Empleado de logistica\n y eliminarlo del sistema");
            return;
        }else {
            String identificacion = txtIdBuscar.getText();
            try{
                controlador.eliminarEmpleadoLog(identificacion);
                JOptionPane.showMessageDialog(null, "Empleado de logistica eliminado correctamente");
                limpiarCampos();
                actualizarTabla();
            }catch(IdentificacionNoExisteException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        panelEliminar.setBackground(new Color(100, 128, 152));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        panelEliminar.setBackground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtEdad.getText().trim().length() == 2){
            evt.consume();
        }
      }//GEN-LAST:event_txtEdadKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtIdentificacion.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtTelefono.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTarjetaProfesionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarjetaProfesionalKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtTarjetaProfesional.getText().trim().length() == 20){
            evt.consume();
        }  
    }//GEN-LAST:event_txtTarjetaProfesionalKeyTyped

    private void txtAniosExperienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAniosExperienciaKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtAniosExperiencia.getText().trim().length() == 2){
            evt.consume();
        }  
    }//GEN-LAST:event_txtAniosExperienciaKeyTyped

    private void txtIdBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdBuscarKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if(!numeros){
            evt.consume();
        }
        if(txtIdBuscar.getText().trim().length() == 10){
            evt.consume();
        }  
    }//GEN-LAST:event_txtIdBuscarKeyTyped

    public void limpiarCampos() {
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtEdad.setText(null);
        txtIdentificacion.setText(null);
        cboGenero.setSelectedIndex(0);
        txtTelefono.setText(null);
        txtTarjetaProfesional.setText(null);
        txtRutasAsignadas.setText(null);
        txtAniosExperiencia.setText(null);
        txtCorreo.setText(null);
        txtContrasenia.setText(null);
        txtConfirmarContrasenia.setText(null);
        txtIdBuscar.setText(null);
    }
    
    private void actualizarTabla(){
        LSE<EmpleadoLogistica> capitanes = controlador.conseguirEmpleados();
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }   
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < capitanes.size() ; i++) {
                    EmpleadoLogistica aux = capitanes.get(i);                   
                    Object[] ob = {aux.getNombres(), aux.getApellidos(), aux.getIdentificacion(), aux.getGenero(), aux.getAniosExperiencia(), aux.getNumeroTarjetaProfesional()};
                    modelo.addRow(ob);                    
                }
            }catch(NullPointerException e){        
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCrearCuenta;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnLimpiar;
    private javax.swing.JMenu btnRegresar3;
    private javax.swing.JMenu btnVolver3;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel20;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelLimpiar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAniosExperiencia;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtConfirmarContrasenia;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRutasAsignadas;
    private javax.swing.JTextField txtTarjetaProfesional;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
