package VistasViajero;

import Controladores.ControladorVerAvion;
import Modelos.Avion;
import Modelos.Reserva;
import Modelos.Viajero;
import Modelos.Vuelo;
import Util.LSE;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author diaza
 */
public class VentanaReservaVueloViajero extends javax.swing.JFrame implements ActionListener {

    private Viajero viajero;
    private Vuelo vuelo;
    private ControladorVerAvion controlador;
    JButton[][] botones;
    
    /**
     * Creates new form VentanaReservaVueloViajero
     */
    public VentanaReservaVueloViajero(Viajero viajero, Vuelo vuelo) {
        initComponents();
        this.viajero = viajero;
        this.vuelo = vuelo;
        this.controlador = new ControladorVerAvion();
        Avion avion = vuelo.getAvion();
        if (avion != null) { 
            int columnas = 0;
            if (avion.getBloque() == 2) {
                columnas = 4;
            } else {
                columnas = 6;
            }
            botones = new JButton[avion.getFila()][columnas];
            cargarAsientos();
        } else {
        }
        modificarAsientos(vuelo.getListaReservas());
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVolver = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 92, 117));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver.setText("Mas opciones");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnVolver.add(btnRegresar);

        jMenuBar1.add(btnVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        this.dispose();
        JFrame v2 = new VentanaVuelosProgramados(viajero);
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolverMouseReleased
   
    private void cargarAsientos() {
        int ancho = 55;
        int alto = 55;
        int separado = 30;
        int separadoAlt = 25;
        int texto = 1;
        boolean espacioEnMedio = true;

        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                botones[i][j].setBounds(
                    (j * ancho + separado),
                    (i * alto + separadoAlt),
                    ancho, alto);
                botones[i][j].setText(String.valueOf(texto));
                botones[i][j].addActionListener(this);
                jPanel1.add(botones[i][j]);
                texto++;

                if (espacioEnMedio && j == botones[i].length / 2 - 1) {
                    separado += ancho; 
                }
            }
            separado = 30;
            separadoAlt += 7;
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        JButton boton = (JButton) e.getSource();

        if (boton.getBackground() == Color.BLUE) {
            
        }else if (boton.getBackground() == Color.WHITE) {
            int numeroAsiento = Integer.parseInt(boton.getText());
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea reservar el asiento #" + numeroAsiento + "?", "Reservar asiento", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    controlador.generarReserva(numeroAsiento,vuelo ,viajero);
                    modificarAsientos(vuelo.getListaReservas());
                    bloquear();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }else if(boton.getBackground() == Color.GREEN){
            JOptionPane.showMessageDialog(null, "Este asiento esta reservado por usted"
                    + "\n La información es "
                    + "\n Nombres y apellidos: "+ viajero.getNombres() + " " + viajero.getApellidos()
                    + "\n Número de identificación: " + viajero.getIdentificacion()
                    + "\n Edad: " + viajero.getEdad()
                    + "\n Género: " + viajero.getGenero()
                    + "\n Teléfono: " + viajero.getNumTelefono()
                    + "\n Pais de nacimiento: " + viajero.getPaisNacimiento());
        }
    }
    
    public void modificarAsientos(LSE<Reserva> listaReservas) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                JButton boton = botones[i][j];
                int numeroAsiento = Integer.parseInt(boton.getText());
                boolean estaReservado = controlador.verificarReserva(numeroAsiento, vuelo.getListaReservas());
                boolean estaReservado2 = controlador.verificarReservaPropia(numeroAsiento, vuelo.getListaReservas(), viajero);
                if (estaReservado && !estaReservado2) {   
                    boton.setBackground(Color.BLUE);
                }else if(estaReservado && estaReservado2){    
                    boton.setBackground(Color.GREEN);
                }else {                 
                    boton.setBackground(Color.WHITE); 
                }
            }
        }
    }
     
    public void bloquear(){
        
        LSE<Reserva> contador = controlador.validar1ReservaVuelo(viajero, vuelo);
        
        if(contador.size() >= 1) {
            JOptionPane.showMessageDialog(null, "Ha cumplido el máximo de 1 reserva por vuelo");
            for (int i = 0; i < botones.length; i++) {
                for (int j = 0; j < botones[i].length; j++) {
                    JButton boton = botones[i][j];
                    int numeroAsiento = Integer.parseInt(boton.getText());
                    boolean estaReservado = controlador.verificarReserva(numeroAsiento, vuelo.getListaReservas());
                    boolean estaReservado2 = controlador.verificarReservaPropia(numeroAsiento, vuelo.getListaReservas(), viajero);
                    if (estaReservado && !estaReservado2) {   
                        boton.setBackground(Color.BLUE);
                    }else if(estaReservado && estaReservado2){    
                        boton.setBackground(Color.GREEN);
                    }else {                 
                        boton.setEnabled(false); 
                    }
                }
            }
        }        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnRegresar;
    private javax.swing.JMenu btnVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
