package VistasEmpleadoLogistica;

import Controladores.ControladorVentanaSolicitarMantenimiento;
import Excepciones.CruzaHorariosMantenimientoException;
import Excepciones.SolicitudYaEnviadaException;
import Excepciones.YaExisteCodigoMantenimientoException;
import Modelos.Aerolinea;
import Modelos.Avion;
import Modelos.EmpleadoLogistica;
import Modelos.Mantenimiento;
import Util.LSE;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diaza
 */
public class VentanaSolicitarMantenimiento extends javax.swing.JFrame {

    private EmpleadoLogistica empleadoLogistica;
    private ControladorVentanaSolicitarMantenimiento controlador;
    DefaultTableModel modelo;
    
    /**
     * Creates new form VentanaSolicitarMantenimiento
     */
    public VentanaSolicitarMantenimiento(EmpleadoLogistica empleadoLogistica) {
        initComponents();
        this.empleadoLogistica = empleadoLogistica;
        this.controlador = new ControladorVentanaSolicitarMantenimiento();
        actualizarComboBoxAviones();
        modelo = (DefaultTableModel)tabla.getModel();
        dataFecha.setMinSelectableDate(new Date());
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboAviones = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        dataFecha = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtDetalles = new javax.swing.JTextField();
        btnMantenimiento = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVolver = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(65, 92, 117));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Detalles");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, -1));

        cboAviones.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(cboAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(65, 92, 117));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Solicitar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mante.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 70, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(65, 92, 117));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mantenimiento");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(65, 92, 117));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Aviones de la Aerolínea");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, -1));
        jPanel1.add(dataFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 150, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(65, 92, 117));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Número");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 20));
        jPanel1.add(txtDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, 60));

        btnMantenimiento.setBackground(new java.awt.Color(65, 92, 117));
        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnMantenimiento.setText("Solicitar");
        btnMantenimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 150, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 90, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Fecha Fin", "Avion", "Detalles", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, 110));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(65, 92, 117));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Seleccione la fecha");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 170, -1));
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(65, 92, 117));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(65, 92, 117));
        btnVolver.setText("Mas opciones");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVolverMouseReleased(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(65, 92, 117));
        btnRegresar.setForeground(new java.awt.Color(65, 92, 117));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoVolver.png"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnVolver.add(btnRegresar);

        jMenuBar1.add(btnVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuPrincipalEmpleadoLogistica(empleadoLogistica);
        v2.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        btnVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseReleased
        btnVolver.setForeground(new Color(65, 92, 117));
    }//GEN-LAST:event_btnVolverMouseReleased

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        if(txtDetalles.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese los detalles para registrar enviar la solicitud");
            return;
        }
        
        if(txtNum.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese el numero de solicitud");
            return;
        }
        
        if(cboAviones.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Seleccione un avión");
            return;
        }
        
        if(dataFecha.getDate() == null){
            JOptionPane.showMessageDialog( null , "Debe escoger una fecha para agendar el mantenimiento");
            
        }else{
            String detalles = txtDetalles.getText();
            Date x = dataFecha.getDate();
            LocalDate dia = new  java.sql.Date(x.getTime()).toLocalDate();
            
            String avionSeleccionado = String.valueOf(cboAviones.getSelectedItem());
            int numeroAvion = Integer.parseInt(avionSeleccionado);
            Avion avionRecibido = controlador.buscarNumeroAvion(numeroAvion);
            Aerolinea aerolineaRecibida = controlador.buscarAerolineaPersona(empleadoLogistica.getIdentificacion());
            int num = Integer.parseInt(txtNum.getText());
            
            Mantenimiento mantenimiento = new Mantenimiento(num, detalles, dia, avionRecibido, "Pendiente");
            
            try{
                controlador.nuevaSolicitud(aerolineaRecibida, mantenimiento, avionRecibido);
                JOptionPane.showMessageDialog(null, "Se agrego correctamente la solicitud");
                limpiarCampos();
                actualizarTabla();
            }catch(YaExisteCodigoMantenimientoException | SolicitudYaEnviadaException | CruzaHorariosMantenimientoException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    public void limpiarCampos(){
        cboAviones.setSelectedIndex(0);
        dataFecha.setDate(null);
        txtDetalles.setText(null);   
        txtNum.setText(null);
    }
    
    private void actualizarTabla() {
        Aerolinea aerolinea = controlador.buscarAerolineaPersona(empleadoLogistica.getIdentificacion());
        LSE<Mantenimiento> mantenimientos = controlador.obtenerMantenimiento(aerolinea);

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        for (int i = 0; i < mantenimientos.size(); i++) {
            Mantenimiento aux = mantenimientos.get(i);
            Object[] ob = {aux.getFechaInicio(), aux.getFechaFin(), aux.getAvion().getNumero(), aux.getMotivo(), aux.getEstado()};
            modelo.addRow(ob);
        }
    }  
      
    public void actualizarComboBoxAviones() {
        cboAviones.removeAllItems();
        Aerolinea aerolinea = controlador.buscarAerolineaPersona(empleadoLogistica.getIdentificacion());
        LSE<String> lista = new LSE<>();

        try {
            LSE<Avion> listaAviones = controlador.conseguirAviones(aerolinea);
            for (int i = 0; i < listaAviones.size(); i++) {
                Avion avion = listaAviones.get(i);
                String nombres = String.valueOf(avion.getNumero());
                lista.add(nombres);
            }
            cboAviones.addItem("-Seleccionar-");
            for (int i = 0; i < lista.size(); i++) {
                String item = lista.get(i);
                cboAviones.addItem(item);
            }
        } catch (Exception e) {
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JMenu btnRegresar;
    private javax.swing.JMenu btnVolver;
    private javax.swing.JComboBox<String> cboAviones;
    private com.toedter.calendar.JDateChooser dataFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtDetalles;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
